### ISSUE TITLE
Modules update: Shopify(maybe other modules as well) module are used when Orgs module in updated

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1017]

**Comment by AntonLV** [comment]
The issue appears because of Updater uses '**process_page_triggers**' and '**process_menu_triggers**' actions. Each of them retrieves a list of all modules and tries to find necessary service method in Module class.
`BxDolRequest::serviceExists($aModule['name'],` 'get_menu_set_name_for_menu_trigger')
