### ISSUE TITLE
Studio Forms: additional custom language keys are created even when it's not needed

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1352]
https://una.io/page/view-discussion?id=1010
---

How to reproduce:

- clean install (or use ci.una.io/test)
- go to Polyglot > select "Custom" module > check if anything is here
- go to Forms > Fields > Module: Persons > Display: Add Person > click "edit" for "Birthday" fields then save without making any changes
- go to Polyglot > select "Custom" module > you will see that "_bx_persons_form_profile_input_sys_birthday" keys were added as custom fields

**Comment by AntonLV** [comment]
1. The issue described in Discussion relates to Search form and language keys in it. Yes, keys are generated automatically as copies from similar fields from Add\Edit content forms. It's performed during module installation. It's needed because field caption in Add form may differ from the caption of the same field in Add\Edit forms. We autogenerate keys to allow Operater to use different Captions in such fields.
2. The issue described here (edit "Birthday" field ...) appears because language keys are moved from Persons category to Custom category when the field was updated. Even if nothing was changed in translation language key is updated.

**Comment by AntonLV** [comment]
1. It works as it should.
2. Language Key shouldn't be moved in Custom category during making changes in a field in Forms Builder.

**Comment by AlexTr** [comment]
@AntonLV Situation is very very bad, for some reason it even deletes system language keys!!! for example `_sys_form_input_location` was deleted, and `_sys_form_input_location_1531980402` was added instead as custom key. It needs to be resolved as soon as possible!

**Comment by AntonLV** [comment]
The issue may appear for modules which were installed a long time ago. In the very first version of Extended Search language keys didn't automatically duplicated on Search Form auto generation. So, real keys from Add/Edit forms were used in Extended Search form. After some time Extended Search become to duplicate keys to allow to change translations separately for fields in Add/Edit and Search forms. Duplicated keys are deleted and regenarated again when Extended Search is reset via Studio -> Forms -> Search Forms. So, the problem shouldn't appear on fresh installed sites.

**Comment by AntonLV** [comment]
On the next RC: The content of sys_search_extended_fields table should be updated. Non-duplicated keys like _sys_form_input_location (all keys which don't have timestamp at the end) should be auto updated to have duplicates.

**Comment by AlexTr** [comment]
https://github.com/unaio/una/commit/db1990a6ac076f40bcd026812b6a5a0c032f4abc
