### ISSUE TITLE
Auto-generate 3 albums for Timline, Profile and Cover in ALBUMS app.

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#1449]
Auto-generated Albums like "Profile Images", "Timeline Images" and "Cover Images" that automatically duplicate the uploads made to respective modules.

**Comment by AlexTr** [comment]
It's impossible in UNA structure, copying isn't solution.

**Comment by kreativmind** [comment]
I wish it were because even posting to timeline will not make pictures available for display using Latest Photos block. It's not very useful because so many ways to upload photos but each method chosen to upload has different results and none of the results are to go into a default folder---> subfolder

**Comment by AlexTr** [comment]
@kreativmind you can disable posting photos into timeline, and allow to post Albums only then you will have photos in one place, it's better to use less features(modules) which are focused on your site niche. We have new "united post" form which looks like "post to timeline" block so it will be very similar behaviour like in posting into timeline.
![screen shot 2018-07-19 at 12 01 50 pm](https://user-images.githubusercontent.com/3324866/42917376-9d60fb12-8b4c-11e8-9895-8da5a0774dbb.png)
