### ISSUE TITLE
Update default values for fields in 'sys_objects_grid' table if they are NULL and change field type by adding default value

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1673]
Other tables maybe affected too

**Comment by AntonLV** [comment]
The issue represents in all newly added grids (at least on una.io) which where added in the DB after `order_get_field`, `order_get_dir` and `filter_get` fields were added in the `sys_objects_grid` table. The issue appears because of the following:
1. In system.sql these fields in `sys_objects_grid` table have default values 'order_field', 'order_dir' and 'filter' accordingly. 
2. In una.io DB these fields don't have default values. Looks like it happened during one of the previous upgrades and should be fixed during the next one.

**Comment by AlexTr** [comment]
https://github.com/unaio/una/commit/a698a794e6cd4973ec369eb978049ef9e1e16936
