### ISSUE TITLE
Notifications: not translated language key in notifications settings

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1705]
_bx_ntfs_alert_action_medias_added_follow_member

https://una.io/page/view-discussion?id=1704

**Comment by AntonLV** [comment]
Notification settings related to old Albums' alert action 'media_added', which aren't used since RC11, should be removed during the next update. The settings have the following titles:
1. _bx_albums_alert_action_media_added_follow_member
2. _bx_albums_alert_action_media_added_follow_context

So, we need to execute the following MySQL query:
> DELETE FROM `bx_notifications_settings` WHERE `title` IN ('_bx_albums_alert_action_media_added_follow_context', '_bx_albums_alert_action_media_added_follow_member');
