### ISSUE TITLE
Google connect: use "google" icon instead of "google plus" icon

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2343]
https://una.io/page/view-discussion?id=3735

**Comment by punyauk** [comment]
See https://developers.google.com/identity/branding-guidelines

**Comment by punyauk** [comment]
I see this is marked as closed yet I tried using the latest version on Github and it still doesn't match the 'Sign-In Branding Guidelines '
![googlebtns](https://user-images.githubusercontent.com/8977917/64125369-9e410200-cda1-11e9-98fb-a2c947e33b3c.png)

**Comment by punyauk** [comment]
Just to re-iterate,  the Google connect module is still broken and does not meet Google branding so new users will find they can not get authorization for it.  This is the email Google sent me:

Dear Developer,
--
Thank you for submitting an OAuth App Verification request. To proceed with the verification process, please update your project queersociallogin-1xx7396x18x7 to comply with our requirements.

Please update the Google sign-in button on your project’s homepage URL so that it complies with the Google sign-in branding guidelines. Once your project is updated to reflect these requirements, please reply to this email to confirm your compliance. If you have additional questions, you can review the OAuth Application Verification FAQ or respond to this email.
