### ISSUE TITLE
Reactions: Improve user experiance.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#2948]
Clicking "like" should just do the basic like option (without having to select it in a dropdown menu). Hover or long press (mobile) to access the full menu of other options.

m752916

**Comment by siremystic** [comment]
Though I think it's preferable to leave it as it is now.....since it takes a bit of effort to actually react to post. Hence making users actually want to click the like button because they really like the post. This drives down to real-time reaction result unlike with most social media with fake likes on every post that comes the users' feeds. In addition, it's best admin should be able to activate/deactivate feature to click "like button right away" or pop a dropdown menu.

**Comment by AntonLV** [comment]
Settings were added in Studio -> Settings -> Site Settings -> Enable 'Quick Reactions' mode
