### ISSUE TITLE
Recommendations are not filled on API create/account login 

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#4572]
0/1202915123164593/1205968096256237

browse_recommendations_fans not fill using UNA/NEO

**Comment by AntonLV** [comment]
Update Recommendations transient cron is executed after login
![изображение](https://github.com/unaio/una/assets/3894360/041a8ae6-554d-4a65-b11c-15b71f2d4333)
but it doesn't after join. It happens because Create Account flow, which is used in the APP, doesn't initiate the standard login process (doesn't call **bx_login** method).

**Comment by AntonLV** [comment]
Now Update Recommendations process is initiated after profile creation too. Checked on Web version.
