### ISSUE TITLE
New Sub-Pages for Home

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#517]
Add the new pages and link to them via sub-menu in Homepage.

1. **Overview** 
Gateway page for initial basic site overview. Shows a Splash block for custom HTML, and login/signup blocks at the bottom for guests.

2. **Community**
Page with a mix of blocks from various modules: people, posts, albums, discussions, Outline, etc.

3. **Timeline** 
Single-block page with vertical site-wide Timeline and "Post to Timeline" blocks.

4. **Pulse**
Blocks with charts and activity spy. In most cases these will be configured to be visible by admins only, but can be made public.

**Comment by andreyasko** [comment]
We already have the page for Timeline, and Community, Pulse are largely just custom pages, but we need them to be pre-made by default to streamline the homepage setup for UNA webmasters.

**Comment by AlexTr** [comment]
1. We already have overview Splash page, which can be enabled in Studio settings, it's shown for not logged in users.
2. Actually this is site homepage now.
3. Timeline page is already there, but there is link to it from "+" menu only, since it's already on homepage by default.
4. We don't have charts yet, but will add it, there is an issue for it:
https://github.com/unaio/una/issues/363

**Comment by andreyasko** [comment]
Main point is to be able to have a submenu on homepage, which can be used for general site-browning pages like community, all-featured, Timeline or Outline (pure) or Pulse. We can have it off or empty by default, but there's benefit in having it available.

**Comment by AntonLV** [comment]
Note. Currently there is no a separate page for Home page Timeline/Outline. We have such page for Profile page Timeline/Outline.

**Comment by AlexTr** [comment]
We've already have homepage menu, but it's in separate block. If we place it in submenu I think it will not look logical, since this menu is connected to site menu. 

If it's needed I would suggest to add needed pages to the version, and menu can be made via page builder and menu builder - we have menu block in page builder so it can be added via Studio interface.

**Comment by andreyasko** [comment]
Sound good. Just add the pages and we'll build the needed menu at UNA.io as a demo.

**Comment by AntonLV** [comment]
Ticket #517 - Home page Timeline.
