### ISSUE TITLE
Notifications module update

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#623]
1. Don't separate My content & My subscriptions. It should be one list with all notifications and one alert counter.
2. Check the notification when somebody subscribes to your profile.
3. Make sure that main actions are displayed properly for own and subscribed profiles (something is posted, comment to your content, like, etc).

**Comment by AlexTr** [comment]
4) No notification when Discussion topic posted, reply posted or like by person you are subscribed to. 

Also when reposting Discussion, it displays as "Alex reposted a timeline post" - without any name and link to the discussion.



5) When posting something to timeline then it shows in Notification as:
	- "Alex added a new timeline post \_Alex added post_" - when posting text (or text + something)
	- "Alex added a new timeline post \_Alex added a post_" - when posting link, photo, video without text

I think that when text is posted then instead of "Alex added post" display first N letters from the text then 3 dots, when text isn't posted then display "link", "photo", "video" words, or combination of them.

6) When person you are subscribed to posts comment/vote to the Image in the Album it isn't showing in Notifications, for the Album it works fine.

7) Is it possible to add notification when the person you are subscribed to get new friend ?

8) When reposting, it is displayed as 
"Alex reposted a timeline post \_Galaxy added a post_", I think it should be "Alex reposted _Galaxy_ post"
"Alex reposted a timeline post Online.me added an album" , I think it should be "Alex reposted \_AlbumNameHere_ post" (or  \_AlbumNameHere_ album, if possible)
same for other content

9) Different issue -  why there is no Like and Social sharing buttons for Market Products ?

10) Warning: array_merge(): Argument #2 is not an array in /Users/alex/www/hihi/una/modules/boonex/timeline/classes/BxTimelineTemplate.php on line 1174

There are a lot of reposted posts in timeline, it maybe it's because of reposted File, since it looks like it isn't implemented properly ?

11) "Abc added a new \_timeline post's comment_ to \_Alex reposted Alex's poll_" should be 
"Abc added a new \_timeline post's comment_ to \_PollNameHere_".

12) No notification when comment or like is posted to my Post, Product, Poll.

13) Is it possible to add notification when somebody replies to your comment ?
