### ISSUE TITLE
When no username is specified - display account ID

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#777]
It's needed for situations when username field is optional in account registration form

**Comment by andrewboon** [comment]
Further related improvements in Sign-up form:

- [x] Make "Account name" optional in Forms builder.
- [x] Make "Receive news" optional
- [x] Make "Agreement" optional
- [x] Move social login buttons to their own separate block.

**Only email and password** should be required at this stage. Later, we can add "generated password" email that works as a confirmation email as well. Then, only email would be a required field. 

"Account name" is largely redundant, since it's not unique and may be confused as a login-username. UNA doesn't accept account name at login, so it only makes things more confusing. Operators can add extra identification fields via Forms builder if required at account-stage registration.

"Agreement" notice may also not be needed in many cases, or may be better positioned outside of the signup form. For example, as a pop-over along with "cookies" agreement, or as a separate custom underneath the signup form. 

"Receive news" is often not needed when newsletters are handled by separate subscription service subscribe form (Mailchimp) or not used at all. Site notifications are not newsletters and don't need opt-in. 

Social login buttons work both as sign-up and sign in, so it's also best to have them in a separate block, which can be positioned anywhere as needed, or used a sole form of authentication.
