### ISSUE TITLE
transcoder won't work

### ISSUE THREAD

**Issue by ZsgsDesign** [unacms/UNA#805]
https://mundb.xyz/image_transcoder.php?o=bx_organizations_avatar&h=1&dpx=2&t=1502873279
returned a 404 error.
I checked the code,finding that
`if (!$oTranscoder->isFileReady($sHandler) && !$oTranscoder->transcode ($sHandler)) {
    bx_transcoder_error_occured();
    exit;
}`
is the reason that lead to 404. But I don't understand why the resize fails.

**Comment by AlexTr** [comment]
To resize the image, transcoder need to get the original image, it gets the image by URL.

So I would suggest to check if it's allowed to open URLs of your site from your site, since it's forbidden on some hosts. In this case usually it helps to add the following line into /etc/hosts file (in case on *nix platforms):
```
127.0.0.1    mundb.xyz
```

**Comment by ZsgsDesign** [comment]
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

My hosts file already have some strange items like this.

**Comment by AlexTr** [comment]
just add one more line

**Comment by ZsgsDesign** [comment]
I have tried but it didn't work. Maybe there is someting wrong with Nginx?

**Comment by AlexTr** [comment]
Yes, it maybe related to Nginx configuration, could you please check if original images are displaying ?

You can check original images displaying in Studio > Storage, just upload file and try to open it by the provided URL

Rewrite rules for Nginx:
https://una.io/page/view-discussion?id=133
